import type {
  Patient,
  Encounter,
  Appointment,
  LabOrder,
  RadiologiOrder,
  Resep,
  DischargeSummary,
  SyncLog,
  AppUser,
} from "./types";

// ─────────────────────────────────────────────
// Users / Roles
// ─────────────────────────────────────────────
export const MOCK_USERS: AppUser[] = [
  { id: "u1", nama: "dr. Rendra Pratama, Sp.PD", role: "dokter", unit: "Poli Penyakit Dalam" },
  { id: "u2", nama: "dr. Nadia Kusuma, Sp.A",    role: "dokter", unit: "Poli Anak" },
  { id: "u3", nama: "Siti Rahayu, AMd.Kep",       role: "perawat", unit: "Poli Umum" },
  { id: "u4", nama: "Budi Santoso",               role: "admin", unit: "Pendaftaran" },
  { id: "u5", nama: "Farida Nur",                 role: "apoteker", unit: "Apotek" },
  { id: "u6", nama: "Ahmad Fauzi",                role: "lab", unit: "Laboratorium" },
  { id: "u7", nama: "Dewi Lestari",               role: "manajemen", unit: "Manajemen" },
];

// ─────────────────────────────────────────────
// Patients
// ─────────────────────────────────────────────
export const MOCK_PATIENTS: Patient[] = [
  {
    id: "p1",
    noRM: "NRM.07.001",
    noIHS: "P02029221AAAA",
    nik: "3201234567890001",
    nama: "Agus Setiawan",
    tanggalLahir: "1978-03-15",
    jenisKelamin: "L",
    telepon: "08123456789",
    alamat: "Jl. Merdeka No. 12, Bogor",
    status: "aktif",
    syncStatus: "tersinkron",
    createdAt: "2026-01-10T08:00:00Z",
    updatedAt: "2026-07-15T10:00:00Z",
  },
  {
    id: "p2",
    noRM: "NRM.07.002",
    noIHS: "P02029221BBBB",
    nik: "3271234567890002",
    nama: "Ratna Dewi",
    tanggalLahir: "1990-07-22",
    jenisKelamin: "P",
    telepon: "08234567890",
    alamat: "Jl. Sudirman No. 45, Jakarta",
    status: "aktif",
    syncStatus: "tersinkron",
    createdAt: "2026-02-05T09:00:00Z",
    updatedAt: "2026-07-18T09:00:00Z",
  },
  {
    id: "p3",
    noRM: "NRM.07.003",
    noIHS: undefined,
    nik: "3578901234560003",
    nama: "Hendra Wijaya",
    tanggalLahir: "1965-11-30",
    jenisKelamin: "L",
    telepon: "08345678901",
    alamat: "Jl. Pahlawan No. 7, Bandung",
    status: "aktif",
    syncStatus: "belum_sync",
    createdAt: "2026-03-12T11:00:00Z",
    updatedAt: "2026-07-20T07:00:00Z",
  },
  {
    id: "p4",
    noRM: "NRM.07.004",
    noIHS: "P02029221CCCC",
    nik: "3471234567890004",
    nama: "Sari Indah Lestari",
    tanggalLahir: "1985-05-08",
    jenisKelamin: "P",
    telepon: "08456789012",
    alamat: "Jl. Flamboyan No. 3, Surabaya",
    status: "aktif",
    syncStatus: "gagal",
    createdAt: "2026-04-01T08:30:00Z",
    updatedAt: "2026-07-19T14:00:00Z",
  },
  {
    id: "p5",
    noRM: "NRM.07.005",
    noIHS: "P02029221DDDD",
    nik: "3201098765430005",
    nama: "Budi Rahardjo",
    tanggalLahir: "1950-08-12",
    jenisKelamin: "L",
    telepon: "08567890123",
    alamat: "Jl. Veteran No. 21, Depok",
    status: "nonaktif",
    syncStatus: "tersinkron",
    createdAt: "2025-11-01T07:00:00Z",
    updatedAt: "2026-05-10T08:00:00Z",
  },
  {
    id: "p6",
    noRM: "NRM.07.006",
    noIHS: "P02029221EEEE",
    nik: "3372109876540006",
    nama: "Maya Putri Andini",
    tanggalLahir: "2001-02-14",
    jenisKelamin: "P",
    telepon: "08678901234",
    alamat: "Jl. Cempaka No. 9, Semarang",
    status: "aktif",
    syncStatus: "tersinkron",
    createdAt: "2026-05-20T09:00:00Z",
    updatedAt: "2026-07-20T10:00:00Z",
  },
  {
    id: "p7",
    noRM: "NRM.07.007",
    noIHS: "P02029221FFFF",
    nik: "3201234009870007",
    nama: "Dodi Firmansyah",
    tanggalLahir: "1973-09-25",
    jenisKelamin: "L",
    telepon: "08789012345",
    alamat: "Jl. Kenanga No. 17, Tangerang",
    status: "aktif",
    syncStatus: "tersinkron",
    createdAt: "2026-06-01T08:00:00Z",
    updatedAt: "2026-07-20T08:30:00Z",
  },
  {
    id: "p8",
    noRM: "NRM.07.008",
    noIHS: undefined,
    nik: "3509876543210008",
    nama: "Nurul Hidayah",
    tanggalLahir: "1995-12-03",
    jenisKelamin: "P",
    telepon: "08890123456",
    alamat: "Jl. Anggrek No. 5, Bekasi",
    status: "aktif",
    syncStatus: "belum_sync",
    createdAt: "2026-07-10T10:00:00Z",
    updatedAt: "2026-07-20T09:00:00Z",
  },
];

// ─────────────────────────────────────────────
// Appointments
// ─────────────────────────────────────────────
export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: "a1",
    patientId: "p1",
    patientNama: "Agus Setiawan",
    patientNoRM: "NRM.07.001",
    dokterId: "u1",
    dokterNama: "dr. Rendra Pratama, Sp.PD",
    tanggal: "2026-07-20",
    jam: "08:00",
    keluhan: "Batuk dan sesak napas 3 hari",
    status: "checked_in",
    createdAt: "2026-07-18T09:00:00Z",
  },
  {
    id: "a2",
    patientId: "p2",
    patientNama: "Ratna Dewi",
    patientNoRM: "NRM.07.002",
    dokterId: "u1",
    dokterNama: "dr. Rendra Pratama, Sp.PD",
    tanggal: "2026-07-20",
    jam: "08:30",
    keluhan: "Kontrol gula darah rutin",
    status: "booked",
    createdAt: "2026-07-19T10:00:00Z",
  },
  {
    id: "a3",
    patientId: "p6",
    patientNama: "Maya Putri Andini",
    patientNoRM: "NRM.07.006",
    dokterId: "u2",
    dokterNama: "dr. Nadia Kusuma, Sp.A",
    tanggal: "2026-07-20",
    jam: "09:00",
    keluhan: "Demam 2 hari, pilek",
    status: "booked",
    createdAt: "2026-07-19T14:00:00Z",
  },
  {
    id: "a4",
    patientId: "p3",
    patientNama: "Hendra Wijaya",
    patientNoRM: "NRM.07.003",
    dokterId: "u1",
    dokterNama: "dr. Rendra Pratama, Sp.PD",
    tanggal: "2026-07-20",
    jam: "10:00",
    keluhan: "Nyeri dada sebelah kiri",
    status: "booked",
    createdAt: "2026-07-20T07:00:00Z",
  },
  {
    id: "a5",
    patientId: "p4",
    patientNama: "Sari Indah Lestari",
    patientNoRM: "NRM.07.004",
    dokterId: "u2",
    dokterNama: "dr. Nadia Kusuma, Sp.A",
    tanggal: "2026-07-19",
    jam: "09:30",
    keluhan: "Nyeri perut bawah",
    status: "done",
    createdAt: "2026-07-18T08:00:00Z",
  },
  {
    id: "a6",
    patientId: "p7",
    patientNama: "Dodi Firmansyah",
    patientNoRM: "NRM.07.007",
    dokterId: "u1",
    dokterNama: "dr. Rendra Pratama, Sp.PD",
    tanggal: "2026-07-19",
    jam: "11:00",
    keluhan: "Kontrol hipertensi",
    status: "cancelled",
    createdAt: "2026-07-17T10:00:00Z",
  },
];

// ─────────────────────────────────────────────
// Encounters
// ─────────────────────────────────────────────
export const MOCK_ENCOUNTERS: Encounter[] = [
  {
    id: "e1",
    noEncounter: "ENC.20260720.001",
    patientId: "p1",
    patientNama: "Agus Setiawan",
    patientNoRM: "NRM.07.001",
    dokterId: "u1",
    dokterNama: "dr. Rendra Pratama, Sp.PD",
    perawatId: "u3",
    perawatNama: "Siti Rahayu, AMd.Kep",
    tipe: "clinic_visit",
    status: "in_progress",
    tanggal: "2026-07-20",
    keluhan: "Batuk dan sesak napas 3 hari",
    vitalSign: {
      tekananDarah: "130/85",
      nadiPerMenit: 92,
      suhuc: 37.8,
      beratKg: 72,
      tinggicm: 168,
      spo2: 96,
      respirasiPerMenit: 20,
    },
    syncStatus: "belum_sync",
    modulesCompleted: ["asesmen"],
    createdAt: "2026-07-20T08:05:00Z",
    updatedAt: "2026-07-20T09:30:00Z",
  },
  {
    id: "e2",
    noEncounter: "ENC.20260720.002",
    patientId: "p6",
    patientNama: "Maya Putri Andini",
    patientNoRM: "NRM.07.006",
    dokterId: "u2",
    dokterNama: "dr. Nadia Kusuma, Sp.A",
    tipe: "clinic_visit",
    status: "draft",
    tanggal: "2026-07-20",
    keluhan: "Demam 2 hari, pilek",
    syncStatus: "belum_sync",
    modulesCompleted: [],
    createdAt: "2026-07-20T09:00:00Z",
    updatedAt: "2026-07-20T09:00:00Z",
  },
  {
    id: "e3",
    noEncounter: "ENC.20260719.001",
    patientId: "p4",
    patientNama: "Sari Indah Lestari",
    patientNoRM: "NRM.07.004",
    dokterId: "u2",
    dokterNama: "dr. Nadia Kusuma, Sp.A",
    tipe: "clinic_visit",
    status: "finished",
    tanggal: "2026-07-19",
    keluhan: "Nyeri perut bawah",
    vitalSign: {
      tekananDarah: "110/70",
      nadiPerMenit: 78,
      suhuc: 37.2,
      beratKg: 56,
      tinggicm: 160,
      spo2: 99,
      respirasiPerMenit: 18,
    },
    syncStatus: "tersinkron",
    modulesCompleted: ["asesmen", "lab", "resep", "discharge"],
    createdAt: "2026-07-19T09:35:00Z",
    updatedAt: "2026-07-19T14:00:00Z",
  },
  {
    id: "e4",
    noEncounter: "ENC.20260718.001",
    patientId: "p2",
    patientNama: "Ratna Dewi",
    patientNoRM: "NRM.07.002",
    dokterId: "u1",
    dokterNama: "dr. Rendra Pratama, Sp.PD",
    tipe: "clinic_visit",
    status: "finished",
    tanggal: "2026-07-18",
    keluhan: "Kontrol gula darah — HbA1c rutin",
    vitalSign: {
      tekananDarah: "120/80",
      nadiPerMenit: 74,
      suhuc: 36.8,
      beratKg: 63,
      tinggicm: 158,
      spo2: 98,
      respirasiPerMenit: 16,
    },
    syncStatus: "tersinkron",
    modulesCompleted: ["asesmen", "lab", "resep", "discharge"],
    createdAt: "2026-07-18T08:00:00Z",
    updatedAt: "2026-07-18T12:00:00Z",
  },
  {
    id: "e5",
    noEncounter: "ENC.20260715.001",
    patientId: "p3",
    patientNama: "Hendra Wijaya",
    patientNoRM: "NRM.07.003",
    dokterId: "u1",
    dokterNama: "dr. Rendra Pratama, Sp.PD",
    tipe: "home_visit",
    status: "finished",
    tanggal: "2026-07-15",
    keluhan: "Kunjungan rumah — pasien post-op",
    syncStatus: "gagal",
    modulesCompleted: ["asesmen", "resep"],
    createdAt: "2026-07-15T10:00:00Z",
    updatedAt: "2026-07-15T12:00:00Z",
  },
  {
    id: "e6",
    noEncounter: "ENC.20260720.003",
    patientId: "p8",
    patientNama: "Nurul Hidayah",
    patientNoRM: "NRM.07.008",
    dokterId: "u1",
    dokterNama: "dr. Rendra Pratama, Sp.PD",
    tipe: "clinic_visit",
    status: "in_progress",
    tanggal: "2026-07-20",
    keluhan: "Nyeri kepala berulang, mual",
    vitalSign: {
      tekananDarah: "145/90",
      nadiPerMenit: 88,
      suhuc: 36.9,
      beratKg: 58,
      tinggicm: 162,
      spo2: 98,
      respirasiPerMenit: 18,
    },
    syncStatus: "belum_sync",
    modulesCompleted: ["asesmen", "lab"],
    createdAt: "2026-07-20T10:00:00Z",
    updatedAt: "2026-07-20T11:00:00Z",
  },
];

// ─────────────────────────────────────────────
// Lab Orders
// ─────────────────────────────────────────────
export const MOCK_LAB_ORDERS: LabOrder[] = [
  {
    id: "l1",
    encounterId: "e1",
    patientId: "p1",
    namaTest: "Darah Lengkap (DL)",
    prioritas: "rutin",
    status: "completed",
    result: {
      parameter: [
        { nama: "Hemoglobin", nilai: "11.2", satuan: "g/dL", referenceRange: "12.0–16.0", flag: "low" },
        { nama: "Leukosit", nilai: "12500", satuan: "/µL", referenceRange: "4000–11000", flag: "high" },
        { nama: "Trombosit", nilai: "235000", satuan: "/µL", referenceRange: "150000–400000", flag: "normal" },
        { nama: "Hematokrit", nilai: "34", satuan: "%", referenceRange: "37–47", flag: "low" },
      ],
      completedAt: "2026-07-20T10:30:00Z",
    },
    createdAt: "2026-07-20T09:00:00Z",
  },
  {
    id: "l2",
    encounterId: "e1",
    patientId: "p1",
    namaTest: "CRP (C-Reactive Protein)",
    prioritas: "rutin",
    status: "processing",
    createdAt: "2026-07-20T09:05:00Z",
  },
  {
    id: "l3",
    encounterId: "e3",
    patientId: "p4",
    namaTest: "Urine Lengkap",
    prioritas: "rutin",
    status: "completed",
    result: {
      parameter: [
        { nama: "Leukosit Urine", nilai: "++", satuan: "", referenceRange: "Negatif", flag: "high" },
        { nama: "Nitrit", nilai: "+", satuan: "", referenceRange: "Negatif", flag: "high" },
        { nama: "Protein", nilai: "Trace", satuan: "", referenceRange: "Negatif", flag: "normal" },
      ],
      completedAt: "2026-07-19T11:30:00Z",
    },
    createdAt: "2026-07-19T10:00:00Z",
  },
  {
    id: "l4",
    encounterId: "e4",
    patientId: "p2",
    namaTest: "HbA1c",
    prioritas: "rutin",
    status: "completed",
    result: {
      parameter: [
        { nama: "HbA1c", nilai: "7.8", satuan: "%", referenceRange: "< 7.0", flag: "high" },
        { nama: "Gula Darah Sewaktu", nilai: "185", satuan: "mg/dL", referenceRange: "70–140", flag: "high" },
      ],
      completedAt: "2026-07-18T10:00:00Z",
    },
    createdAt: "2026-07-18T08:30:00Z",
  },
  {
    id: "l5",
    encounterId: "e6",
    patientId: "p8",
    namaTest: "Darah Lengkap + Elektrolit",
    prioritas: "rutin",
    status: "sample_collected",
    createdAt: "2026-07-20T10:15:00Z",
  },
];

// ─────────────────────────────────────────────
// Radiology Orders
// ─────────────────────────────────────────────
export const MOCK_RADIOLOGY_ORDERS: RadiologiOrder[] = [
  {
    id: "r1",
    encounterId: "e1",
    patientId: "p1",
    modalitas: "X-Ray",
    bodyPart: "Thorax PA",
    klinis: "Batuk produktif, sesak napas, leukositosis",
    status: "completed",
    interpretasi: "Infiltrat perihilar bilateral, kesan pneumonia.",
    createdAt: "2026-07-20T09:10:00Z",
  },
  {
    id: "r2",
    encounterId: "e6",
    patientId: "p8",
    modalitas: "CT Scan",
    bodyPart: "Kepala non-kontras",
    klinis: "Nyeri kepala berulang, mual, TD 145/90",
    status: "scheduled",
    createdAt: "2026-07-20T10:20:00Z",
  },
];

// ─────────────────────────────────────────────
// Prescriptions
// ─────────────────────────────────────────────
export const MOCK_PRESCRIPTIONS: Resep[] = [
  {
    id: "rx1",
    encounterId: "e3",
    patientId: "p4",
    dokterNama: "dr. Nadia Kusuma, Sp.A",
    status: "completed",
    items: [
      {
        id: "rxi1",
        namaObat: "Ciprofloxacin",
        dosis: "500 mg",
        frekuensi: "2x sehari",
        durasi: "7 hari",
        instruksi: "Sesudah makan",
        jumlah: 14,
      },
      {
        id: "rxi2",
        namaObat: "Paracetamol",
        dosis: "500 mg",
        frekuensi: "3x sehari",
        durasi: "5 hari",
        instruksi: "Jika nyeri atau demam",
        jumlah: 15,
      },
    ],
    createdAt: "2026-07-19T12:00:00Z",
  },
  {
    id: "rx2",
    encounterId: "e4",
    patientId: "p2",
    dokterNama: "dr. Rendra Pratama, Sp.PD",
    status: "completed",
    items: [
      {
        id: "rxi3",
        namaObat: "Metformin",
        dosis: "500 mg",
        frekuensi: "2x sehari",
        durasi: "30 hari",
        instruksi: "Bersama makan",
        jumlah: 60,
      },
      {
        id: "rxi4",
        namaObat: "Glibenklamid",
        dosis: "5 mg",
        frekuensi: "1x sehari",
        durasi: "30 hari",
        instruksi: "Sebelum makan pagi",
        jumlah: 30,
      },
    ],
    createdAt: "2026-07-18T11:00:00Z",
  },
];

// ─────────────────────────────────────────────
// Discharge Summaries
// ─────────────────────────────────────────────
export const MOCK_DISCHARGES: DischargeSummary[] = [
  {
    id: "d1",
    encounterId: "e3",
    patientId: "p4",
    diagnosisUtama: { kode: "N39.0", nama: "Infeksi Saluran Kemih" },
    obatLanjutan: [
      {
        id: "rxi1",
        namaObat: "Ciprofloxacin",
        dosis: "500 mg",
        frekuensi: "2x sehari",
        durasi: "7 hari",
        instruksi: "Sesudah makan",
        jumlah: 14,
      },
    ],
    metodePulang: "pulang_biasa",
    jadwalKontrol: "2026-07-26",
    ringkasanKlinis:
      "Pasien datang dengan keluhan nyeri perut bawah disertai BAK nyeri 3 hari. Hasil urine lengkap menunjukkan leukosituria dan nitrit positif. Diberikan antibiotik empiris. Kondisi membaik.",
    dokterNama: "dr. Nadia Kusuma, Sp.A",
    createdAt: "2026-07-19T13:30:00Z",
  },
];

// ─────────────────────────────────────────────
// SatuSehat Sync Logs
// ─────────────────────────────────────────────
export const MOCK_SYNC_LOGS: SyncLog[] = [
  { id: "s1", resourceType: "Patient",  resourceId: "p1", resourceLabel: "Agus Setiawan (NRM.07.001)", status: "tersinkron", lastAttempt: "2026-07-20T08:05:00Z", retryCount: 0 },
  { id: "s2", resourceType: "Encounter", resourceId: "e4", resourceLabel: "ENC.20260718.001 — Ratna Dewi", status: "tersinkron", lastAttempt: "2026-07-18T12:05:00Z", retryCount: 0 },
  { id: "s3", resourceType: "Patient",  resourceId: "p3", resourceLabel: "Hendra Wijaya (NRM.07.003)", status: "belum_sync", lastAttempt: "2026-07-20T07:00:00Z", retryCount: 0 },
  { id: "s4", resourceType: "Encounter", resourceId: "e5", resourceLabel: "ENC.20260715.001 — Hendra Wijaya", status: "gagal", lastAttempt: "2026-07-15T13:00:00Z", errorMessage: "FHIR server timeout: 504 Gateway Timeout", retryCount: 3 },
  { id: "s5", resourceType: "Patient",  resourceId: "p4", resourceLabel: "Sari Indah Lestari (NRM.07.004)", status: "gagal", lastAttempt: "2026-07-19T15:00:00Z", errorMessage: "Invalid No. IHS format — validation failed", retryCount: 2 },
  { id: "s6", resourceType: "Encounter", resourceId: "e3", resourceLabel: "ENC.20260719.001 — Sari Indah Lestari", status: "tersinkron", lastAttempt: "2026-07-19T14:05:00Z", retryCount: 0 },
  { id: "s7", resourceType: "Patient",  resourceId: "p8", resourceLabel: "Nurul Hidayah (NRM.07.008)", status: "belum_sync", lastAttempt: "2026-07-20T10:00:00Z", retryCount: 0 },
  { id: "s8", resourceType: "Encounter", resourceId: "e1", resourceLabel: "ENC.20260720.001 — Agus Setiawan", status: "belum_sync", lastAttempt: "2026-07-20T09:30:00Z", retryCount: 0 },
  { id: "s9", resourceType: "DiagnosticReport", resourceId: "l1", resourceLabel: "Darah Lengkap — Agus Setiawan", status: "tersinkron", lastAttempt: "2026-07-20T10:35:00Z", retryCount: 0 },
  { id: "s10", resourceType: "Observation", resourceId: "l4", resourceLabel: "HbA1c — Ratna Dewi", status: "tersinkron", lastAttempt: "2026-07-18T10:05:00Z", retryCount: 0 },
];

// ─────────────────────────────────────────────
// ICD-10 Quick List (mock subset)
// ─────────────────────────────────────────────
export const ICD10_LIST = [
  { kode: "J18.9", nama: "Pneumonia, unspecified" },
  { kode: "J06.9", nama: "Infeksi Saluran Napas Atas Akut" },
  { kode: "E11.9", nama: "Diabetes Melitus Tipe 2 tanpa komplikasi" },
  { kode: "I10",   nama: "Hipertensi Esensial" },
  { kode: "N39.0", nama: "Infeksi Saluran Kemih" },
  { kode: "K29.7", nama: "Gastritis, unspecified" },
  { kode: "R51",   nama: "Nyeri Kepala" },
  { kode: "M79.3", nama: "Panniculitis" },
  { kode: "J45.9", nama: "Asma, unspecified" },
  { kode: "A09",   nama: "Diare dan Gastroenteritis infeksius" },
  { kode: "B06.9", nama: "Rubella tanpa komplikasi" },
  { kode: "L03.9", nama: "Selulitis, unspecified" },
  { kode: "K80.2", nama: "Kolelitiasis tanpa kolesistitis" },
  { kode: "I21.9", nama: "Infark Miokard Akut, unspecified" },
  { kode: "G43.9", nama: "Migrain, unspecified" },
];
